name: 'blog_project'
description: 'A Library for create blog super easy and fast customizable'
version: '0.0.1'
repository: 'https://github.com/azkadev/blog'
homepage: 'https://github.com/azkadev/blog'
issue_tracker: 'https://github.com/azkadev/blog/issues'
blog: 'https://github.com/azkadev/blog/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '>=3.3.3 <4.0.0'
dependencies: 
  general_lib: '^0.0.46'
  mason_logger: '^0.3.1'
  packagex: '^0.0.60'
  path: '^1.9.0'
  universal_io: '^2.2.2'
  yaml: '^3.1.2'
  yaml_edit: '^2.2.0'
  yaml_writer: '^2.0.0'
dev_dependencies: 
  lints: '^4.0.0'
  test: 'any'
dependency_overrides: 
  pointycastle: '3.8.0'
documentation: 'https://youtube.com/@azkadev'
